spring:
  datasource:
    url: jdbc:mysql://localhost:3306/destination
    username: root
    password: password
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints
  endpoint:
    health:
      show-details: "always"  # Expose full health details
