# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    # Run docker compose
    - name: Set up Docker Compose
      run: docker-compose up -d

    # Wait for MySQL to be ready
    - name: Wait for MySQL to be ready
      run: |
        until docker-compose logs mysql | grep "ready for connections"; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    # Wait for Kafka to be ready
    - name: Wait for Kafka to be ready
      run: |
        until docker-compose logs kafka-broker | grep "started (kafka.server.KafkaServer)"; do
          echo "Waiting for Kafka to be ready..."
          sleep 5
        done

    # Run and test both demos
    - name: Build demo-db-to-kafka with Maven
      run: mvn -B package -f demo-db-to-kafka/pom.xml

    - name: Run tests for demo-db-to-kafka
      run: mvn -f demo-db-to-kafka/pom.xml test

    - name: Build demo-kafka-to-db with Maven
      run: mvn -B package -f demo-kafka-to-db/pom.xml

    - name: Run tests for demo-kafka-to-db
      run: mvn -f demo-kafka-to-db/pom.xml test
    
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    
